In [ ]:
import numpy as np

# Task 1

In the tasks the variables t1,...,tn usually indicates the variable assigned for that task unless specified in the question otherwise. The variable t1 creates a 1D array or row vector populated with zeros

In [ ]:
t1=np.zeros(10)
t1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Task 2

In this task we create a 2D array or matrix of size 7x6 and then we reshape the matrix to 3x14 using reshape method of numpy

In [ ]:
t2=np.zeros((7,6))
t2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
t2.shape

(7, 6)

In [ ]:
t2.reshape((3,14))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# Task 3

In this task we essentially find the indices of the elements that have an odd value, we do this in the basic method using a loop and checking whether the mod 2 gives 1 or 0, if 1 then odd otherwise even
np.arange essentially creates a row vector of size 10 and populates it with values from 0..9

In [ ]:
t3=np.arange(10)
t3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in t3:
  if(i%2):
    print(i,end=' ')


1 3 5 7 9 

# Task 4
Here we also follow a basic approach of replacing the value of t4$_i$ to -1 whenever the value yield a mod 2 of 1

In [ ]:
t4=np.arange(10)

In [ ]:
for i in range(t4.size):
  if(t4[i]%2):
    t4[i]=-1
t4


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#Task 5

In this task, we essentially use the where method in python to essentially replace selective values that satisfy the condition of mod 2 is not 0 to -1, implying that we replace the odd values to -1

In [ ]:
arr=np.arange(10)
out=np.where(arr%2!=0,arr,-1)
arr,out

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9]))

# Task 6

In this task we follow the approach of essentially comparing two values using a for loop and print the value of the indices where they match accordingly. Then in the next approach we follow a more optimal approach of using a numpy method to compute the equal indices

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
for i in range(min(a.size,b.size)):
  if(a[i]==b[i]):
    print(i,end=' ')

1 3 5 7 

In [ ]:
index=np.where(np.equal(a,b))
index

(array([1, 3, 5, 7]),)

# Task 7

We use the row vector given in the question and then we filter the indexes with the right values and then we take the values of the following indices from our original given array t6

In [ ]:
t6 = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:
indexes=np.where(np.logical_and(t6>=5,t6<=10))
np.take(t6,indexes,0)

array([[ 6,  9, 10]])

# Task **8**
We first create 2 arrays using numpy zeros and numpy ones and then we concatenate them accordingly

In [ ]:
t71=np.zeros(10)
t72=np.ones(10)
t71,t72

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
t73=np.concatenate([t71,t72])
t73

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
t71.np.reshape(t71,(10,1))
t72=np.reshape(t71,(10,1))
t73=np.concatenate([[t71],[t72]])
t71,t72,t73

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))

# Task 9

We created a 5x4 matrix of random values less than 10

In [ ]:
t8=np.random.randint(10,size=(5,4))
t8

array([[7, 3, 2, 1],
       [9, 5, 1, 6],
       [4, 2, 9, 8],
       [8, 8, 8, 7],
       [7, 8, 5, 5]])

# Task 10

We creates a row vector y, with random values between 0 and 1, with a size of n_samples

In [ ]:
n_samples = 5
n_features = 4
X = np.random.rand(n_samples, n_features)
y = np.random.randint(0, 2, n_samples)
print("x = ",X)
print("y = ",y)

x =  [[0.40222882 0.67183608 0.04959557 0.17887262]
 [0.44719513 0.66773864 0.01822081 0.58915906]
 [0.57920403 0.64176213 0.20556792 0.90601352]
 [0.41199989 0.48588517 0.79850976 0.28368088]
 [0.12590617 0.39974006 0.3898422  0.11336233]]
y =  [0 1 1 0 1]


# Task 11

We created a function to filter the subset of values that match the sample values 0 and 1 and we only take those rows or those columns respectively

In [ ]:
def extract_subset(X, y, y0):
  res=[]
  for i in range(y.size):
    if(y[i]==y0):
      res.append(X[i,:])
  return res


In [ ]:
extract_subset(X,y,0)

[array([0.40222882, 0.67183608, 0.04959557, 0.17887262]),
 array([0.41199989, 0.48588517, 0.79850976, 0.28368088])]

# Task 12

Import Iris data using scikit learn library and view the data

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# Task 13

In this task we find the mean, standard deviation, median, max and min as forms of data aggregation

In [ ]:
np.mean(iris.data[:,0])

5.843333333333334

In [ ]:
np.std(iris.data[:,0])

0.8253012917851409

In [ ]:
np.median(iris.data[:,0])

5.8

In [ ]:
np.var(iris.data[:,0])

0.6811222222222223

In [ ]:
np.max(iris.data[:,0])

7.9

In [ ]:
np.min(iris.data[:,0])

4.3